In [ ]:
## Name - Nikhil 
 ## assignment -4 (Numpy)

In [2]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8,9])
print(ar)

[1 2 3 4 5 6 7 8 9]


In [3]:
#version numpy

In [4]:
import numpy as np
print(np.__version__)

2.1.1


In [5]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8])
print(ar)


[1 2 3 4 5 6 7 8]


In [6]:
#dimension in array

In [7]:
#0d array
import numpy as np
ar=np.array(30)
print(ar)

30


In [8]:
#1d array

In [9]:
import numpy as np
ar = np.array([1,2,3,4,5,7,8,9])
print(ar)

[1 2 3 4 5 7 8 9]


In [10]:
#2d array

In [11]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#3d array 

In [13]:
import numpy as np
ar = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(ar)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [14]:
#count dimension

In [15]:
import numpy as np
a =np.array(42)
b =np.array([1,2,3,4,5])
c =np.array([[1,2,3],[4,5,6]])
d =np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [16]:
import numpy as np 
ar=np.array([1,2,3,4,],ndmin=5)
print(ar)
print("no. of dimensions ",ar.ndim)

[[[[[1 2 3 4]]]]]
no. of dimensions  5


In [17]:
#array index

In [18]:
# 1st element
import numpy as np
ar= np.array([1,2,3,4])
print(ar[0])

1


In [19]:
#2nd element 
import numpy as np
ar=np.array([1,2,3,4])
print(ar[1])

2


In [20]:
import numpy as np
ar=np.array([1,2,3,4])
print(ar[2]+ar[3])

7


In [21]:
#access 2d array

In [22]:
import numpy as np
ar= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:',ar[0,1])

2nd element on 1st row: 2


In [23]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('4th element on 2nd row: ',ar[1,3])

4th element on 2nd row:  9


In [24]:
import numpy as np
ar=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(ar[0,1,2])

6


In [25]:
# negative indexing

In [26]:
import numpy as np
ar= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element from 2nd dim: ', ar[1,-1])

Last element from 2nd dim:  10


In [27]:
import numpy as np
ar = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Last element: ', ar[1,:]) # : for last 

Last element:  [ 6  7  8  9 10]


In [28]:
#slicing array

In [29]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7])
print(ar[1:5])

[2 3 4 5]


In [30]:
#negative slicing

In [31]:
import numpy as np
ar= np.array([1,2,3,4,5,6,7,8,9,0])
print(ar[-3:-1])

[8 9]


In [32]:
# for last slicing
import numpy as np
ar= np.array([1,2,3,4,5,6,7,8,9,0])
print(ar[-3:])

[8 9 0]


In [33]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8,9,0])
print(ar[1:5:2])

[2 4]


In [34]:
import numpy as np
ar= np.array([1,2,3,4,5,6,7,8,9])
print(ar[::2])

[1 3 5 7 9]


In [35]:
#slicing 2d array

In [36]:
import numpy as np
ar=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(ar[1,1:4])

[7 8 9]


In [37]:
import numpy as np
ar= np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(ar[0:2,3])

[4 9]


In [38]:
ar= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ar[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [39]:
ar=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(ar[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [40]:
# data type in numpy

In [41]:
import numpy as np
ar=np.array([1,2,3,4])
print(ar.dtype)

int64


In [42]:
ar= np.array(['qwe','asd','zxc'])
print(ar.dtype)

<U3


In [43]:
#create array with defined data type

In [44]:
import numpy as np
ar=np.array([1,2,3,4,5,6],dtype='S')
print(ar)
print(ar.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [45]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8,8],dtype='i4')
print(ar)
print(ar.dtype)

[1 2 3 4 5 6 7 8 8]
int32


In [46]:
#converting data type

In [47]:
import numpy as np
ar= np.array([1.1,2.1,3.1])
newar=ar.astype('i')
print(newar)
print(newar.dtype)

[1 2 3]
int32


In [48]:
# float to integer

In [49]:
import numpy as np
ar=np.array([1.1,2.1,3.1])
newar= ar.astype(int)
print(newar)
print(newar.dtype)

[1 2 3]
int64


In [50]:
#integer to boolean

In [51]:
import numpy as np
ar= np.array([1,0,3])
newar=arr.astype(bool)
print(newar)
print(newar.dtype)

[[ True  True  True  True  True]
 [ True  True  True  True  True]]
bool


In [52]:
# array copy,view

In [53]:
import numpy as np
ar= np.array([1,2,3,4,5,6,7,8])
z=ar.copy()
ar[0]=11
print(ar)
print(z)

[11  2  3  4  5  6  7  8]
[1 2 3 4 5 6 7 8]


In [54]:
import numpy as np
ar= np.array([1,2,3,4,5,6,7,8,9,0])
z= ar.view()
ar[0]=42
print(ar)
print(z)

[42  2  3  4  5  6  7  8  9  0]
[42  2  3  4  5  6  7  8  9  0]


In [55]:
#array reshaping

In [56]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
newar=ar.reshape(4,3)
print(newar)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [57]:
# 1d to 3d

In [58]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newar=ar.reshape(2,3,2)
print(newar)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [59]:
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
newar=ar.reshape(10,2,1)
print(newar)

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]

 [[13]
  [14]]

 [[15]
  [16]]

 [[17]
  [18]]

 [[19]
  [20]]]
